Fix output directory for copied byproducts
corrosion-rs/corrosion pull request #568
Opened 2024-10-08 03:43 UTC by obsgolem

CMake doesn't automatically append the config type to the output dir when using a custom command.

2024-10-08 12:34 UTC, jschwe commented
I'm curious what the background of this PR is. Did you experience an issue with a multi-config generator?

2024-10-08 14:18 UTC, obsgolem commented
Yes, I am having an issue where an executable is being copied to my `build` directory, not my `build/Debug` (or whatever) directory. This is with the VS generator. Some tests are failing, so I need to see if that is due to it assuming the behavior I was seeing, or if the behavior I was seeing is due to something complex I haven't found yet.

2024-10-10 19:10 UTC, obsgolem commented
Apologies for the lockfile changes, don't know what is up with them. Want me to revert them?

2024-11-01 13:39 UTC, jschwe reviewed
> I am having an issue where an executable is being copied to my build directory, not my build/Debug (or whatever) directory. This is with the VS generator. Some tests are failing, so I need to see if that is due to it assuming the behavior I was seeing, or if the behavior I was seeing is due to something complex I haven't found yet.

What kind of tests are failing? Corrosions tests or tests from your project?
I guess changing the default location the artifact is copied to in Multi-Config mode has the potential to break user code, so we would need to document it in the release notes and also give a short reason what this change fixes.

2024-11-01 14:20 UTC, obsgolem commented on test/output directory/output directory/CMakeLists.txt
> +    ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_PROPERTY:rust_bin1,LOCATION_$<CONFIG>>" "${CMAKE_CURRENT_BINARY_DIR}/another_dir/moved_bin"
The CMake docs just have the general statement "generator expressions can be nested". As far as I am aware this pretty much always works. I can look for some examples in the stuff that ships with CMake if that would assuage doubts.

2024-11-01 14:20 UTC, obsgolem commented
> What kind of tests are failing? Corrosions tests or tests from your project?
> I guess changing the default location the artifact is copied to in Multi-Config mode has the potential to break user code, so we would need to document it in the release notes and also give a short reason what this change fixes.

The output directory tests *were* failing, but after a couple rounds of revision I managed to fix that.

2024-11-19 18:25 UTC, obsgolem commented
Failing test is not due to me I think

2024-11-23 13:42 UTC, jschwe requested changes
Looking at this again, I noticed that we unconditionally append the config_type now, when the expected behavior is to only append the config_type if the OUTPUT_DIRECTORY variable is not a generator expression

2024-11-23 13:42 UTC, jschwe commented on cmake/Corrosion.cmake
> +            set(curr_out_dir "${output_directory}/${config_type}")
I think we would need to check if `output_directory` contains a generator expression, and only when it **does not**, then append `${config_type}` to match the expected behavior (see e.g. https://cmake.org/cmake/help/latest/prop_tgt/RUNTIME_OUTPUT_DIRECTORY.html)

2024-12-11 05:56 UTC, jschwe approved these changes

2024-12-11 06:09 UTC, merged

2024-12-11 06:10 UTC, jschwe commented
Thanks! And sorry for the long review times

2024-12-11 06:16 UTC, obsgolem commented
Hey, if you can put up with long times between me responding to review, I can put up with long review times, thanks!